name: Cargo Check

on:
  push:
    branches:
      - main

jobs:
  cargo-check:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install protoc
        run: |
          brew install protobuf

      - name: Run cargo check
        run: cargo check
